### ISSUE TITLE
Start script for existing recordings?

### ISSUE THREAD

**Issue by blu-IT** [danielpetri1/bbb-recording-exporter#32]
Hi,

I copied the files as explained to the server. Do I have to start/trigger the rendering for the videos manually when some recordings **already exist** on the server?

Thanks!

**Comment by hostbbb** [comment]
bbb-record --rebuild a particular meeting will trigger the post_process.rb and generate .mp4,  but the raw archives still need to be on the server.    If you have lots of recordings, DONT do --rebuildall,  and make sure you have a backup of /var/bigbluebutton/published  since the  rebuild deletes the html5 recordings.

the ruby scripts will run at command line... i set the meetingID - ARGV[0] and pass the meeting ID  like ruby render_chat.rb as command line.   think there is a way to also set meetingID in ruby as well.

**Comment by blu-IT** [comment]
OK, thanks!

**Comment by felcaetano** [comment]
You can run scripts manually using:

./render_chat.rb -m **_meetingID_**  -f presentation
./render_cursor.rb -m **_meetingID_**   -f presentation
./render_whiteboard.rb -m **_meetingID_**   -f presentation

Where **_meetingID_**  is your... you know... meetingID. And the scripts must run in this exact order. 

I'm not sure if you need the meeting raw files. Maybe you just need the published ones. (I can test it later)

**Comment by felcaetano** [comment]
As @hostbbb pointed out, rebuilding all is a bad idea if you have lots of recordings.
First, because you'll also rebuild the original html5 recordings. That will consume time and it's unnecessary.
Second, because you won't trigger the export for recordings that you don't have the raw files anymore (By default BBB keep the raw files for 15 days IIRC).

I made a script to export all recordings on my server without rebuilding it. It's a really simple script, but it does the job.
Run it manually and DON'T place it in the "_post_publish_" folder. Run it from somewhere else. 


https://github.com/felcaetano/bbb-recording-exporter/blob/main/export_all.rb

**Comment by blu-IT** [comment]
Thanks!
