### ISSUE TITLE
Integration with scalelite

### ISSUE THREAD

**Issue by aguerson** [danielpetri1/bbb-recording-exporter#4]
Hi guy,

I think it is a really good project.
I need to test it.
Just a suggestion, in your script you download all the file and you recreate the structure you need to create the video file. Why don't just search the file on the BBB instance ( only if you have 1 BBB instance ) or on the scaling tool "scalelite".

In the case of scalelite, all the files of all the BBB instances are re-exported in a NFS server.

So you could adapt your script to just get the files from the directory and do the same.

In a second way, you just need to find a way to start your script each time a new record is ready to be "converted".

To help you in the integration of Greenlight, go here https://github.com/EugeneWHZ/greenlight/commit/e0ced1815b7279342c9eef5d71cb8b78e8a24470

Regards,
Aurelien.

**Comment by danielpetri1** [comment]
Hi @aguerson ,
Thank you for taking a look at my project. It is very much still in its infancy, so your feedback is appreciated.

You are correct that the current code recreates the structure needed to create the video file. That is currently so because I don't have a BBB server running yet, so everything was done client-side.

Once I have a server up and running, the files will be taken from the BBB directories directly.

I hope I understood your question correctly, if not, please let me know. 

I'll take a look into Scalelite, thanks for the suggestion and the link to help with the integration in Greenlight. My idea was not to run the script once a recording is ready to be converted, but rather only once the user wants it through Greenlight's interface to save resources. What do you think?

Regards,
Daniel

**Comment by aguerson** [comment]
> but rather only once the user wants it through Greenlight's interface to save resources. What do you think?

Yes you are right.
I need to test your code to give you me feedback. I am using https://github.com/jibon57/bbb-recorder since a while, and I hope your approach is fastest.

See you soon,
Regards,
Aurelien.

**Comment by pielonet** [comment]
Hi,

I tested your script today and I confirm It is compatible with Scalelite and Greenlight.
Thanks and congratulations,
Thierry

**Comment by danielpetri1** [comment]
Hi @pielonet, that's great to hear, thank you!
