### ISSUE TITLE
File on Processing

### ISSUE THREAD

**Issue by msh13792** [danielpetri1/bbb-recording-exporter#45]
hi
how can i know File on Processing and final output file completed or not?

**Comment by felcaetano** [comment]
You can check the log at "/var/log/bigbluebutton/post_publish.log"

You can also setup a callback URL to notify you. But it requires having a webservice to process it. Check: https://docs.bigbluebutton.org/dev/api.html#recording-ready-callback-url

Right now this callback only works because BBB runs ruby scripts in alphabetical order after each step of the recording process ([source](https://docs.bigbluebutton.org/dev/recording.html#writing-post-scripts)). So "export_presentation.rb" (this project) runs before "post_publish_recording_ready_callback.rb" (which comes along with the BBB).

**Comment by pielonet** [comment]
Hi,
For standard recording processing (presentation), BBB Api sets a parameter "state" with value "processing" for the recording while it is being processed (https://docs.bigbluebutton.org/dev/api.html#getrecordings):

> Since version 1.0 the recording has an attribute that shows a state that Indicates if the recording is [processing|processed|published|unpublished|deleted]. The parameter state can be used to filter results. It can be a set of states separate by commas. If it is not specified only the states [published|unpublished] are considered (same as in previous versions). If it is specified as “any”, recordings in all states are included. 


 Is it also true for your script "Video" ? That is : can I rely on this parameter to know if BBB is still processing mp4 file ?

Kind regards,
Thierry

**Comment by hostbbb** [comment]
If the MP4 recording format, had its own metadata.xml and was structured in folder correctly. then  getRecordings would return the states of presentation, notes, mp4 etc formats when a meetingID was specified.

currently the script just places the mp4 in the presentation folder.

**Comment by pielonet** [comment]
This is really annoying : I have a script that waits for BBB server to finish processing recordings and then shutdowns the server. So I must make sure all recordings are processed including mp4 file.
@danielpetri1 Can you modify this contribution as to have it adhere to the same "format" structure as "presentation" ? You would have to create a "video" format for example. Does it make sense ?

**Comment by danielpetri1** [comment]
Hi @pielonet, I get what you mean: having the exporter as its own separate workflow, instead of an extension to the presentation one. This is how BBB will integrate the script in the 2.5 and beyond version from what I have heard.

In the meantime, you could modify the worker for the process/publish phase of the presentations to call the exporting script so it is part of recording processing (or set your server to shut down after the post-publish scripts are done)

**Comment by danielpetri1** [comment]
Since the script is part of the presentation workflow now, this should be working as requested now
