### ISSUE TITLE
The script does not start

### ISSUE THREAD

**Issue by Vladbooka** [danielpetri1/bbb-recording-exporter#52]
Hey!
Thanks for your project, it helps a lot.
we are using BBB and moodle together, and the resulting video file is available in moodle, but the URL in the metadata.xml file contains an invalid link. the script makes the address like moodle, and we fixed it right in the script. changed # {hostname} to the address of the BBB server.
 line 174 in export_presentation.rb
 metadata.xpath ('recording / playback / link'). children.first.content = "https://bbb.server.ru/presentation/# {meeting_id }/meeting.mp4"

and we had a problem, after installing a clean BBB and added a script and everything worked, but now the script does not start after pudding the record. And the script is launched manually.
How to check the correctness of the automatic launch of the script? where to look? in the log /var/log/bigbluebutton/post_publish.log there are only entries when manually running.

**Comment by danielpetri1** [comment]
Hi Vlad,
Thanks for reaching out. The script has not been tested when integrated in Moodle, only Greenlight. I am glad to hear you found a quick fix that I can implement and share with others.

Is the normal presentation accessible through Moodle? If so that's surprising since the hostname is taken from there... could you please share a screenshot of you're now accessing the video file? Did a button appear in Moodle?

As to why it's not starting automatically anymore: I imagine the script ran manually with root, which changed the permissions of the folders. Chown `/var/log/bigbluebutton/post_publish.log` and `/var/bigbluebutton/published/video/` to `bigbluebutton:bigbluebutton` to fix it. You can check if it's working by recording a presentation for 1 second and see it renders into an MP4.

**Comment by Vladbooka** [comment]
> Is the normal presentation accessible through Moodle? If so that's surprising since the hostname is taken from there... could you please share a screenshot of you're now accessing the video file? Did a button appear in Moodle?

the third link to the Video is highlighted because it was converted before the script was fixed and moodle marked it as unreadable when checking it.
after conversion, moodle reads all options for recording a presentation and displays them on the page.
![image](https://user-images.githubusercontent.com/70394501/134521128-d0bd5825-e426-44ea-a810-85ac38793e9b.png)
